service: lillup
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  profile: lillup
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  environment:
    NEPTUNE_ENDPOINT: neptunedbinstance-1hkuyw35xkor.cuzsrkglqh5g.eu-west-2.neptune.amazonaws.com
    NEPTUNE_PORT: 8182

functions:
  lambdaOne:
    handler: functions/index.handler
    timeout: 30
    events:
      - http:
          path: createProfile
          method: post
          cors: true
         
    vpc:
      securityGroupIds:
        - ${cf:${self:custom.vpcStackName}.VpcDefaultSecurityGroup}
      subnetIds:
        - ${cf:${self:custom.vpcStackName}.Subnet1}
        - ${cf:${self:custom.vpcStackName}.Subnet2}

custom:
  prefix: ${self:service}-${self:provider.stage}
  vpcStackName: lillup-vpc-${self:provider.stage}
